### PR TITLE
Fix invalid texture sizes

### LINKED ISSUE #240: Properly handle dubious texture sizes
There is a `wgpu` issue that we need to work around: https://github.com/gfx-rs/wgpu/issues/1010 I started experimenting with a patch that makes texture creation fallible by checking device limits and changing some APIs to return `Result`.

I ran into a number of problems with automated testing. The big one is that `pixels-mocks` is still not runnable (but it's ok for compilation tests). See #80. Using `winit` in integration tests has some issues with creating the event-loop off the main thread, at least on Windows. It can be done with platform-specific extensions. And then tests may not be able to run on all platforms.

### PR DESCRIPTION
**Pull request by parasyte**
- Makes methods fallible when they create textures.
- Breaking changes:
  - `Pixels::Error` is now marked `#[non_exhaustive]`
  - `Pixels::resize_buffer()` and `Pixels::resize_surface()` return `Result<_, TextureError>`.
  - `Pixels::resize_buffer()` no longer panics on invalid inputs.
- Correctly handle window resize in fltk example.
- TODO: tests
- Closes #240

I haven't written any tests for this, because I still don't have a great solution to the issue raised in #80.

This does add a lot of noise to the examples. I can perhaps address some of that with `Result` transformation methods. The "print error and exit event loop" pattern is very common in these examples but might need more intelligent handling in a real application.

### CODE REVIEW

File: src/builder.rs [hunk 1]
```diff
@@ -347,6 +347,28 @@ impl<'req, 'dev, 'win, W: HasRawWindowHandle> PixelsBuilder<'req, 'dev, 'win, W>
...
+/// # Errors
+///
+/// - [`TextureError::TextureWidth`] when `width` is 0 or greater than GPU texture limits.
+/// - [`TextureError::TextureHeight`] when `height` is 0 or greater than GPU texture limits.
+pub fn check_texture_size(
+    device: &wgpu::Device,
+    width: u32,
+    height: u32,
+) -> Result<(), TextureError> {
+    let limits = device.limits();
```
Comment (parasyte) [inline src/builder.rs:361]: It will probably be better to store the limits in the constructor instead of making this call each time. I don't know what the exact overhead is, but we only need one of many limits here, and the limit is static.
